services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
